version: "3.9"
services:
  rabbit:
    image: "rabbitmq:3.9-management-alpine"
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
  weather-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./src:/src/"
    ports:
      - "3000:3000"
    env_file: ./src/.env
  statistics:
    build:
      context: ./services/statistics
      dockerfile: Dockerfile
    volumes:
      - "./services/statistics:/src/"
    ports:
      - "4000:4000"
    env_file: ./services/statistics/.env
