version: "3.9"
services:
  rabbit:
    image: "rabbitmq:3.9-management-alpine"
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  weather-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./src:/src/"
    ports: 
      - "3000:3000"
    env_file: ./src/.env
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
  statistics:
    build:
      context: ./services/statistics
      dockerfile: Dockerfile
    volumes:
      - "./services/statistics:/src/"
    ports:
      - "4000:4000"
    env_file: ./services/statistics/.env
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
