name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  weather_app_test:
    name: Weather App Test
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./src
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'
      - name: Create env file
        run: |
          touch .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
          cat .env
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  statistics_service_test:
    name: Statistics Service Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/statistics
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
